@startuml
start
:user inputs name or id of animal;
if(user inputs name) then (yes)
    :system retrieves animal by name;
    if( are there animals) then (yes)
        if(is there more than one animal) then (yes)
            :error too many animals;
            end;
        else (no, uses id)
            :return the found animals;
            stop;
        endif

    else(no)
        :error no animals found;
        end;
    endif

else( uses id)
   :system retrieves animal by id;
       if( animal is found) then (yes)
       :return the found animals;
       stop;
       else(no)
           :error no animals found;
           end;

@enduml




